services:
  web:
    build: .
    depends_on:
      - mysql
      - redis
    ports:
      - "8080:8080"
  mysql:
    image: mysql:8.0.33
    container_name: mysql1
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: douyin_projoect
  redis:
    image: redis
    container_name: redis1
    ports:
      - "6579:6579"
