---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- DateTime: 2023/3/20 17:41
---

--- KEYS[1]代表锁的名称
--- ARGV[1]代表GoID+UUID
--- ARGV[2]代表锁的过期时间

if redis.call('HEXISTS',KEYS[1],ARGV[1])==0 then
    return nil
elseif redis.call('HINCRBY',KEYS[1],ARGV[1],-1) ==0 then
    return redis.call('DEL',KEYS[1])

else
    return 0

end